server:
    port: 8080
    error:
        include-stacktrace: never
jms:
    jwt:
        security:
            enabled: true
        timezone: "America/Bogota"
        issuer: "localhost:8585"
        token:
            auth:
                path: "/api/oauth/client_credentials/access_token"
            secret: "vamosAPorMasPuntos"
            expires_in: 3600
        excluded:
            path: "/api/oauth/register,/error,/v3/api-docs" #Para serparar las rutas que no son necesarias autenticar, se separan por comas
spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://sql10.freemysqlhosting.net/sql10515572
        username: sql10515572
        password: 3cmn7KY5CU
        port: 3306
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
